defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: ''

development:
  <<: *defaults
  database: ridegrub_development
test:
  <<: *defaults
  database: ridegrub_test
production:
  <<: *defaults
  database: ridegrub
